server:
  port: 8001
spring:
  data:
    redis:
      host: 8.137.33.37
      port: 6379
      password: yzh@0421
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:static/
short-link:
  stats:
    locate:
      amap-Key: 069017c9ffeb1bc6d82bc132b6a352ae



